CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_title  VARCHAR(255),
    book_author VARCHAR(255),
    description VARCHAR(255),
    price       DECIMAL,
    stock       INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_books PRIMARY KEY (id)
);